version: '3'
services:
  prism:
    image: stoplight/prism:4
    ports:
      - 4010:4010
    command: mock -h 0.0.0.0 /api-specs/swagger.yaml --errors
    volumes:
      - ./swagger.yaml:/api-specs/swagger.yaml